const language = {
  en: {
    title: 'English',
    common: {
      logo: 'Cashier',
      sologon: 'Offline entity store management tool, quick cash efficient inventory, make your store management easier',
      confirm: 'Confirm',
      reset: 'Reset',
      search: 'Search',
      yes: 'Yes',
      no: 'No',
      uploadTips1: 'Click or drag file to this area to upload',
      uploadTips2: 'Support for a single excel file upload.',
      total: 'Total',
      operate: 'Operate',
      operateRemove: 'Remove',
    },
    main: {
      sales: 'Sales',
      order: 'Order Center',
      inventory: 'Inventory Center',
      member: 'Member Center',
      marketing: 'Marketing Center',
      data: 'Data Center',
    },
    user: {
      login: {
        username: 'Username',
        password: 'Password',
        loginBtn: 'Login',
        goRegister: 'no account, register first',
      },
      register: {
        username: 'Username',
        password: 'Password',
        repeatPassword: 'Repeat',
        registerBtn: 'Register',
        goLogin: 'Have account, return to login',
      },
    },
    data: {
      title: 'Summary',
      orderAmount: 'Order Amounts(CNY)',
      orderCount: 'Order Counts',
      itemCount: 'Inventory Counts',
      memberCount: 'Member Counts',
      overview: 'Overview',
      recentSales: 'Recent Sales',
    },
    inventory: {
      title: 'Inventory Center',
      tableTitle: 'Query Results of Inventroys',
      refresh: 'Refresh',
      detailAction: 'Detail',
      detail: 'Inventory Detail',
      itemInfo: 'Item Info',
      skuList: 'The styleNo\'s SKU List',
      search: 'Search',
      add: 'Add',
      edit: 'Edit',
      delete: 'Delete',
      singleStock: 'Single Stock',
      singleStockAction: 'single stock',
      searchLabelSku: 'sku code',
      searchPlaceholderSku: 'input sku code',
      searchLabelStyleNo: 'style no',
      searchPlaceholderStyleNo: 'input style no',
      searchLabelName: 'item name',
      searchPlaceholderName: 'input item name',
      searchLabelBrand: 'item brand',
      searchPlaceholderBrand: 'input item brand',
      tableColumnStyleNo: 'style no',
      tableColumnName: 'item name',
      tableColumnBrand: 'item brand',
      tableColumnSku: 'sku',
      tableColumnColor: 'color',
      tableColumnSize: 'size',
      tableColumnOriginalPrice: 'original price',
      tableColumnCounts: 'counts',
      tableColumnSaleCounts: 'sale counts',
      tableColumnOperation: 'operation',
      editBtn: 'Edit',
      editTitle: 'Item Modify',
      tableColumnCostPrice: 'cost price',
      searchPlaceholderCostPrice: 'input cost price',
      searchPlaceholderCounts: 'input counts',
      searchPlaceholderOriginalPrice: 'input original price',
      searchPlaceholderSize: 'input size',
      searchPlaceholderColor: 'input color',
      bitchStock: 'Batch Stock',
      bitchStockPurchaseTitle: 'Batch Purchase',
      bitchStockPurchaseAction: 'purchase',
      bitchStockPurchaseSubmit: 'submit',
      bitchStockPurchaseCancel: 'cancel',
      bitchStockReturnTitle: 'Batch Returns',
      bitchStockReturnAction: 'returns',
      bitchStockReturnSubmit: 'submit',
      bitchStockReturnCancel: 'cancel',
      bitchStockDownloadTemplate: 'Download Template',
      noStockList: 'No Stock List',
      noStockListAction: 'no stock',
      hotSales: 'Hot Sales',
      hotSalesAction: 'hot sales',
    },
    marketing: {
      title: 'Marketing Center',
      tableTitle: 'Query Results of Marketing',
      refresh: 'Refresh',
      searchLabelMarketingTime: 'time',
      searchLabelMarketingName: 'name',
      searchPlaceholderMarketingName: 'input activity name',
      searchLabelMarketingType: 'type',
      searchPlaceholderMarketingType: 'select activity type',
      searchPlaceholderMarketingDesc: 'input activity description',
      tableColumnName: 'name',
      tableColumnDesc: 'description',
      tableColumnType: 'type',
      tableColumnStartTime: 'start',
      tableColumnEndTime: 'end',
      tableColumnStatus: 'status',
      tableColumnOperation: 'operation',
      tableColumnContent: 'content',
      detailAction: 'Detail',
      detailTitle: 'Marketing Detail',
      marketingInfo: 'Marketing Info',
      marketingCouponList: 'The Marketing\'s Coupon List',
      marketingDetailTitle: 'Marketing Detail',
      marketingName: 'Marketing Name',
      marketingDesc: 'Marketing Description',
      marketingType: 'Marketing Type',
      marketingStartTime: 'Marketing Start Time',
      marketingEndTime: 'Marketing End Time',
      newMarketingTitle: 'New Marketing',
      newMarketingAction: 'New Marketing',
      offlineMarketing: 'Offline Marketing',
      offlineMarketingDescription: 'Are you sure to offline this marketing?',
      offlineAction: 'Offline',
      deleteMarketing: 'Delete Marketing',
      deleteMarketingDescription: 'Are you sure to delete this marketing?',
      deleteMarketingAction: 'Delete',
      modifyTitle: 'Modify Marketing',
      modifyAction: 'Modify',
    },
    member: {
      title: 'Member Center',
      tableTitle: 'Query Results of Members',
      refresh: 'Refresh',
      tableColumnPhone: 'Phone',
      tableColumnName: 'Name',
      tableColumnActual: 'Actual',
      tableColumnPoints: 'Points',
      tableColumnBalance: 'Balance',
      tableColumnCoupon: 'Coupon',
      tableColumnCreatedAt: 'CreatedAt',
      tableColumnOperation: 'Operation',
      tableColumnBirthday: 'Birthday',
      searchLabelCreatedAt: 'create time',
      searchLabelPhone: 'user phone',
      searchPlaceholderPhone: 'input member phone',
      searchPlaceholderName: 'input member name',
      searchPlaceholderBirthday: 'input member birthday',
      searchPlaceholderChangePoint: 'input change point',
      searchPlaceholderChangeType: 'input change type',
      searchPlaceholderChangeReason: 'input change reason',
      searchPlaceholderIncomeBalance: 'input income balance',
      searchPlaceholderSendValue: 'input send value',
      tableColumnSendValueType: 'send value type',
      searchPlaceholderSendValueType: 'select send value type',
      detailAction: 'Detail',
      detailTitle: 'Member Detail',
      detailUserInfo: 'User Info',
      detailUserOrder: 'User Order',
      detailUserPoint: 'User Point',
      detailUserCoupon: 'User Coupon',
      tableColumnCurrentPoint: 'User Point',
      detailUserBalance: 'User Balance',
      tableColumnOrder: 'Order',
      tableColumnAmount: 'Amount',
      tableColumnItems: 'Items',
      tableColumnPayment: 'Payment',
      tableColumnChangeValue: 'Change Value',
      tableColumnChangeType: 'Change Type',
      tableColumnChangeReason: 'Change Reason',
      tableColumnUpdateTime: 'Update Time',
      tableColumnCouponDesc: 'Coupon Desc',
      tableColumnCouponValue: 'Coupon Value',
      tableColumnCouponStatus: 'Status',
      tableColumnCouponExpiredTime: 'Expired Time',
      tableColumnCouponGetTime: 'Get Time',
      modifyTitle: 'Member Modify',
      modifyAction: 'Modify',
      modifyBaseInfo: 'Base Info',
      modifyPoint: 'Point',
      modifyBalance: 'Balance',
      tableColumnInComeBalance: 'Income Balance',
      tableColumnSendValue: 'Send Value',
      tableColumnChangePoint: 'Point Change',
      newJoinTitle: 'New Member',
      newJoinAction: 'New Member',
      incomeBalanceTitle: 'Income Balance',
      incomeBalanceAction: 'Income Balance',
    },
    buy: {
      title: 'Sale and Payment',
      hangUp: 'hang up',
      submit: 'submit',
      clear: 'clear',
      restore: 'restore from handed',
      success: 'success',
      successSubtitle: 'Please confirm the customer\'s payment result at the cashier',
      print: 'print',
      close: 'close',
      marketingInfo: 'Marketing Info',
      userWorth: 'User Worth',
      payment: 'Payment',
      payType: 'Pay Type',
      actual: 'Actual',
      saler: 'Saler',
      remark: 'Remark',
      pleaseSelectSaler: 'please select saler',
      orderRemark: 'order remark',
      inputUserPhone: 'input user phone',
      inputBarcode: 'input barcode',
      scanBarcode: 'scan barcode',
      storeCoupon: 'Store Coupon',
      waitingForSale: 'waiting for sale',
      items: 'items',
      originAmount: 'origin amount',
      shouldPay: 'should pay',
      use: 'use',
      userPoint: 'Points',
      userBalance: 'Balance',
      userCoupon: 'Coupons',
      userBigdayCoupon: 'BigDay',
    },
    order: {
      title: 'Order Center',
      tableTitle: 'Query Results of Orders',
      refresh: 'Refresh',
      checkBill: 'Check Bill',
      checkBillAction: 'Check Bill',
      tableColumnOrderNo: 'Order No',
      tableColumnOrderTime: 'Order Time',
      tableColumnItems: 'Items',
      tableColumnAmount: 'Amount',
      tableColumnActual: 'Actual',
      tableColumnPayment: 'Payment',
      tableColumnUser: 'User',
      tableColumnTime: 'Time',
      tableColumnSaler: 'Saler',
      tableColumnStatus: 'Status',
      tableColumnOperation: 'Operation',
      tableColumnUseCoupon: 'Use Coupon',
      tableColumnUsePoint: 'Use Point',
      tableColumnUseBalance: 'Use Balance',
      tableColumnRemark: 'Remark',
      tableColumnStyleNo: 'Style No',
      tableColumnSkuCode: 'Sku Code',
      tableColumnOriginal: 'Original',
      tableColumnDiscount: 'Discount',
      tableColumnSize: 'Size',
      tableColumnColor: 'Color',
      tableColumnCounts: 'Counts',
      searchLabelOrderSn: 'order code',
      searchPlaceholderOrderSn: 'input order code',
      searchLabelPayType: 'pay channel',
      searchPlaceholderPayType: 'select pay channel',
      searchLabelSalerName: 'saler name',
      searchPlaceholderSalerName: 'select saler name',
      searchLabelCreatedAt: 'create time',
      searchLabelUserPhone: 'user phone',
      searchPlaceholderUserPhone: 'input user phone',
      summaryTitle: 'Query Result of Order\'s Summary',
      summaryOrderAmount: 'Order Amounts(CNY)',
      summaryOrderCount: 'Order Counts',
      summaryItemCount: 'Item Counts',
      summaryOrderAmountByPayChannel: 'Order Amounts by Pay Channel',
      summaryAlipay: 'Alipay',
      summaryWeixin: 'Weixin',
      summaryCash: 'Cash',
      summaryCard: 'Card',
      summaryOther: 'Other',
      queryBySkuCode: 'Query Order by Sku Code',
      queryBySkuCodePlaceholder: 'scan sku code',
      queryBySkuCodeTitle: 'Order List',
      moreOperate: 'More Operate',
      exportAndImport: 'Export and Import',
      importOrder: 'Import Order',
      importOrderBtn: 'Import Order',
      importOrderSubmit: 'Submit',
      importOrderCancel: 'Cancel',
      exportOrder: 'Export Order',
      exportOrderBtn: 'Export Order',
      exportOrderSubmit: 'Submit',
      orderSummary: 'Order Summary',
      orderList: 'Order List',
      detailActual: 'Order Actual Amount',
      detailOrderCount: 'Order Count',
      detailItemCount: 'Item Count',
      detailPayChannelAlipay: 'Pay Channel(alipay)',
      detailPayChannelWeixin: 'Pay Channel(weixin)',
      detailPayChannelCash: 'Pay Channel(cash)',
      detailPayChannelCard: 'Pay Channel(card)',
      detailPayChannelOther: 'Pay Channel(other)',
      orderRefund: 'Order Refund',
      orderRefundBtn: 'Order Refund',
      orderRefundSubmit: 'Submit',
      orderInfo: 'Order Info',
      chooseRefundItems: 'Choose Refund Items',
      inputRefundAmount: 'Input Refund Amount',
      inputRefundAmountPlaceholder: 'Input Refund Amount',
      orderExchange: 'Order Exchange',
      orderExchangeBtn: 'Order Exchange',
      orderExchangeSubmit: 'Submit',
      chooseReturnItems: 'Choose Return Items',
      queryExchangeItems: 'Query Exchange Items',
      queryExchangeItemsPlaceholder: 'scan barcode',
      inputExchangeAmount: 'Input Exchange Amount',
      inputExchangeAmountPlaceholder: 'Input Exchange Amount',
      orderDetail: 'Order Detail',
      orderDetailAction: 'detail',
      orderItems: 'Order Items',
      orderCoupons: 'Order Coupons',
      tableColumnCouponId: 'Coupon ID',
      tableColumnCouponDesc: 'Coupon Desc',
      tableColumnCouponType: 'Coupon Type',
      tableColumnUsedValue: 'Used Value',
      tableColumnUsedTime: 'Used Time',
      orderModify: 'Order Modify',
      orderModifyAction: 'modify',
      billInfo: 'Bill Info',
      printBillAction: 'Print Bill',
      importOrderExtra: 'Only support Order export excel file upload.',
      orderItemListAction: 'Order Items',
      orderItemList: 'Order Item List',
      orderShow: 'Show',
      orderHide: 'Hide',
      tableColumnPrintStatus: 'Print Status',
      confirmBill: 'Confirm Bill',
      tableColumnBillStatus: 'Bill Status',
      tableColumnShowStatus: 'Show Status',
    },
  },
  zh: {
    title: '中文',
    common: {
      logo: '旺店宝',
      sologon: '线下实体店管理工具，快捷收银对账，商品出入库高效盘点，让你的店铺经营更简单',
      confirm: '确定',
      reset: '重置',
      search: '搜索',
      yes: '是',
      no: '否',
      uploadTips1: '点击或拖拽文件到此区域上传',
      uploadTips2: '支持单个excel文件上传',
      total: '总数',
      operate: '操作',
      operateRemove: '移除',
    },
    main: {
      sales: '买单',
      order: '订单中心',
      inventory: '库存中心',
      member: '会员中心',
      marketing: '营销中心',
      data: '数据中心',
    },
    user: {
      login: {
        username: '用户名',
        password: '密码',
        loginBtn: '登录',
        goRegister: '还没有账号，先注册一个',
      },
      register: {
        username: '用户名',
        password: '密码',
        repeatPassword: '重复密码',
        registerBtn: '注册',
        goLogin: '已有账号，返回直接登录',
      },
    },
    data: {
      title: '数据概览',
      orderAmount: '订单金额(CNY)',
      orderCount: '订单数量',
      itemCount: '商品数量',
      memberCount: '会员数量',
      overview: '概览',
      recentSales: '最近买单',
    },
    inventory: {
      title: '库存中心',
      tableTitle: '查询结果',
      refresh: '刷新',
      detailAction: '详情',
      detail: '库存详情',
      itemInfo: '商品信息',
      skuList: '该款下SKU列表',
      search: '搜索',
      add: '新增',
      edit: '编辑',
      singleStock: '新增单件商品',
      singleStockAction: '单件新增',
      searchLabelSku: '条码',
      searchPlaceholderSku: '输入条码',
      searchLabelStyleNo: '款号',
      searchPlaceholderStyleNo: '输入款号',
      searchLabelName: '商品名称',
      searchPlaceholderName: '输入商品名称',
      searchLabelBrand: '品牌',
      searchPlaceholderBrand: '输入品牌',
      tableColumnStyleNo: '款号',
      tableColumnName: '名称',
      tableColumnBrand: '品牌',
      tableColumnSku: '条码',
      tableColumnColor: '颜色',
      tableColumnSize: '尺码',
      tableColumnOriginalPrice: '吊牌价',
      tableColumnCounts: '库存',
      tableColumnSaleCounts: '销量',
      tableColumnOperation: '操作',
      editBtn: '编辑',
      editTitle: '商品编辑',
      tableColumnCostPrice: '成本价',
      searchPlaceholderCostPrice: '输入成本价',
      searchPlaceholderCounts: '输入库存',
      searchPlaceholderOriginalPrice: '输入原价',
      searchPlaceholderSize: '输入尺码',
      searchPlaceholderColor: '输入颜色',
      bitchStock: '批量',
      bitchStockPurchaseTitle: '批量入库',
      bitchStockPurchaseAction: '批量入库',
      bitchStockPurchaseSubmit: '执行入库',
      bitchStockPurchaseCancel: '取消',
      bitchStockReturnTitle: '批量退货',
      bitchStockReturnAction: '批量退货',
      bitchStockReturnSubmit: '执行退货',
      bitchStockReturnCancel: '取消',
      bitchStockDownloadTemplate: '下载模板',
      noStockList: '断码列表',
      noStockListAction: '断码列表',
      hotSales: '热销列表',
      hotSalesAction: '热销榜',
    },
    marketing: {
      title: '营销中心',
      tableTitle: '查询结果',
      refresh: '刷新',
      searchLabelMarketingTime: '活动时间',
      searchLabelMarketingName: '活动名称',
      searchPlaceholderMarketingName: '输入活动名称',
      searchLabelMarketingType: '类型',
      searchPlaceholderMarketingType: '选择活动类型',
      searchPlaceholderMarketingDesc: '输入活动描述',
      tableColumnName: '活动名称',
      tableColumnDesc: '活动描述',
      tableColumnType: '活动类型',
      tableColumnStartTime: '开始时间',
      tableColumnEndTime: '结束时间',
      tableColumnStatus: '状态',
      tableColumnOperation: '操作',
      tableColumnContent: '活动内容',
      marketingInfo: '基本信息',
      marketingCouponList: '优惠券列表',
      marketingDetailTitle: '营销详情',
      detailAction: '详情',
      detailTitle: '营销详情',
      marketingName: '活动名称',
      marketingDesc: '活动描述',
      marketingType: '活动类型',
      marketingStartTime: '开始时间',
      marketingEndTime: '结束时间', 
      marketingCoupon: '名称',
      marketingCouponCondition: '条件',
      marketingCouponValue: '券值',
      marketingCouponCount: '数量',
      marketingCouponStatus: '状态',
      marketingCouponExpiredTime: '过期时间',
      newMarketingTitle: '新增营销活动',
      newMarketingAction: '新增',
      offlineMarketing: '下线营销活动',
      offlineMarketingDescription: '确定要下线该营销活动吗？',
      offlineAction: '下线',
      deleteMarketing: '删除营销活动',
      deleteMarketingDescription: '确定要删除该营销活动吗？',
      deleteMarketingAction: '删除',
      modifyTitle: '修改营销活动',
      modifyAction: '修改',
    },
    member: {
      title: '会员中心',
      tableTitle: '查询结果',
      refresh: '刷新',
      tableColumnPhone: '手机号',
      tableColumnName: '姓名',
      tableColumnActual: '实付',
      tableColumnPoints: '积分',
      tableColumnCurrentPoint: '当前积分',
      tableColumnBalance: '余额',
      tableColumnCoupon: '优惠券',
      tableColumnCreatedAt: '创建时间',
      tableColumnOperation: '操作',
      tableColumnBirthday: '生日',
      searchLabelCreatedAt: '创建时间',
      searchLabelPhone: '手机号',
      searchPlaceholderPhone: '输入会员手机号',
      searchPlaceholderName: '输入会员姓名',
      searchPlaceholderBirthday: '输入会员生日',
      searchPlaceholderChangePoint: '输入变动积分',
      searchPlaceholderChangeType: '输入变动类型',
      searchPlaceholderChangeReason: '输入变动原因',
      searchPlaceholderIncomeBalance: '输入充值金额',
      searchPlaceholderSendValue: '输入赠送金额',
      tableColumnSendValueType: '赠送类型',
      searchPlaceholderSendValueType: '选择赠送类型',
      detailAction: '详情',
      detailTitle: '会员详情',
      detailUserInfo: '会员信息',
      detailUserOrder: '会员订单',
      detailUserPoint: '会员积分',
      detailUserBalance: '会员余额',
      detailUserCoupon: '会员优惠券',
      tableColumnOrder: '订单',
      tableColumnAmount: '应付金额',
      tableColumnItems: '商品数量',
      tableColumnPayment: '支付方式',
      tableColumnChangeValue: '变动值',
      tableColumnChangeType: '变动类型',
      tableColumnChangeReason: '变动原因',
      tableColumnUpdateTime: '变动时间',
      tableColumnCouponDesc: '优惠券描述',
      tableColumnCouponValue: '优惠券值',
      tableColumnCouponStatus: '状态',
      tableColumnCouponExpiredTime: '过期时间',
      tableColumnCouponGetTime: '获取时间',
      modifyTitle: '会员编辑',
      modifyAction: '编辑',
      modifyBaseInfo: '基本信息',
      modifyPoint: '积分',
      modifyBalance: '余额',
      tableColumnInComeBalance: '充值金额',
      tableColumnSendValue: '赠送金额',
      tableColumnChangePoint: '变动积分',
      newJoinTitle: '新增会员',
      newJoinAction: '新增',
      incomeBalanceTitle: '会员充值',
      incomeBalanceAction: '充值',
    },
    buy: {
      title: '买单',
      hangUp: '挂单',
      submit: '提交',
      clear: '清空',
      restore: '恢复挂单',
      success: '买单成功',
      successSubtitle: '请在收银台打印小票',
      print: '打印小票',
      close: '关闭',
      marketingInfo: '营销信息',
      userWorth: '会员资产',
      payment: '支付',
      payType: '支付方式',
      actual: '实付',
      saler: '收银员',
      remark: '备注',
      orderRemark: '订单备注',
      pleaseSelectSaler: '请选择收银员',
      inputUserPhone: '输入会员手机号',
      inputBarcode: '输入条码',
      scanBarcode: '扫描条码',
      storeCoupon: '店铺优惠券',
      waitingForSale: '待售',
      items: '件',
      originAmount: '原价',
      shouldPay: '应付',
      use: '使用',
      userPoint: '积分',
      userBalance: '余额',
      userCoupon: '优惠券',
      userBigdayCoupon: '会员权益',
    },
    order: {
      title: '订单中心',
      tableTitle: '查询结果',
      refresh: '刷新',
      checkBill: '对账',
      checkBillAction: '对账',
      tableColumnOrderNo: '订单号',
      tableColumnOrderTime: '订单时间',
      tableColumnItems: '商品数量',
      tableColumnAmount: '应付金额',
      tableColumnActual: '实付金额',
      tableColumnPayment: '支付方式',
      tableColumnUser: '会员',
      tableColumnTime: '时间',
      tableColumnSaler: '导购员',
      tableColumnStatus: '状态',
      tableColumnOperation: '操作',
      tableColumnUseCoupon: '使用优惠券',
      tableColumnUsePoint: '使用积分',
      tableColumnUseBalance: '使用余额',
      tableColumnRemark: '备注',
      tableColumnStyleNo: '款号',
      tableColumnSkuCode: '条码',
      tableColumnOriginal: '吊牌价',
      tableColumnDiscount: '折扣',
      tableColumnSize: '尺码',
      tableColumnColor: '颜色',
      tableColumnCounts: '数量',
      searchLabelOrderSn: '订单号',
      searchPlaceholderOrderSn: '输入订单号',
      searchLabelPayType: '支付方式',
      searchPlaceholderPayType: '选择支付方式',
      searchLabelSalerName: '导购员',
      searchPlaceholderSalerName: '选择导购员',
      searchLabelCreatedAt: '创建时间',
      searchLabelUserPhone: '会员',
      searchPlaceholderUserPhone: '输入会员手机号',
      summaryTitle: '订单汇总',
      summaryOrderAmount: '订单金额(CNY)',
      summaryOrderCount: '订单数量',
      summaryItemCount: '商品数量',
      summaryOrderAmountByPayChannel: '订单金额按支付方式',
      summaryAlipay: '支付宝',
      summaryWeixin: '微信',
      summaryCash: '现金',
      summaryCard: '银行卡',
      summaryOther: '其他',
      queryBySkuCode: '按SKU查询订单',
      queryBySkuCodePlaceholder: '扫描条码',
      queryBySkuCodeTitle: '订单列表',
      moreOperate: '更多',
      exportAndImport: '导入/导出',
      importOrder: '导入订单',
      importOrderBtn: '导入订单',
      importOrderSubmit: '执行导入',
      importOrderCancel: '取消',
      exportOrder: '导出订单',
      exportOrderBtn: '导出订单',
      exportOrderSubmit: '执行导出',
      orderSummary: '订单汇总',
      orderList: '订单列表',
      detailActual: '订单实付金额',
      detailOrderCount: '订单数量',
      detailItemCount: '商品数量',
      detailPayChannelAlipay: '支付宝',
      detailPayChannelWeixin: '微信',
      detailPayChannelCash: '现金',
      detailPayChannelCard: '银行卡',
      detailPayChannelOther: '其他',
      orderRefund: '订单退货',
      orderRefundBtn: '订单退货',
      orderRefundSubmit: '执行退货',
      orderInfo: '订单信息',
      chooseRefundItems: '选择退货商品',
      inputRefundAmount: '输入退货金额',
      inputRefundAmountPlaceholder: '输入退货金额',
      orderExchange: '订单换货',
      orderExchangeBtn: '订单换货',
      orderExchangeSubmit: '执行换货',
      chooseReturnItems: '选择退货商品',
      queryExchangeItems: '查询换货商品',
      queryExchangeItemsPlaceholder: '扫描条码',
      inputExchangeAmount: '输入换货价差金额',
      inputExchangeAmountPlaceholder: '输入换货价差金额',
      orderDetail: '订单详情',
      orderDetailAction: '详情',
      orderItems: '订单商品',
      orderCoupons: '订单优惠券',
      tableColumnCouponId: '优惠券ID',
      tableColumnCouponDesc: '优惠券描述',
      tableColumnCouponType: '优惠券类型',
      tableColumnUsedValue: '使用金额',
      tableColumnUsedTime: '使用时间',
      orderModify: '修改订单',
      orderModifyAction: '修改',
      billInfo: '小票信息',
      printBillAction: '打印小票',
      importOrderExtra: '只支持导出订单的Excel格式',
      orderItemListAction: '订单商品',
      orderItemList: '订单商品列表',
      orderShow: '对外显示',
      orderHide: '对外隐藏',
      tableColumnPrintStatus: '打印状态',
      confirmBill: '确认到账',
      tableColumnBillStatus: '对账状态',
      tableColumnShowStatus: '对外状态',
    },
  },
};

export default language;